# MYSQL Configuration
url=jdbc:mysql://localhost:3306/bluescope
username=root
password=guna
driver=com.mysql.cj.jdbc.Driver

# HikariCP Configuration
Hikari.maximumPool=10
Hikari.minimumIdle=2
Hikari.idletimeout=3000
Hikari.connectionTimeout=3000
