
driver=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://localhost:3306/bluescope
username=root
password=root

hikari.maximumPoolSize=10

hikari.minimumIdle=2

hikari.idleTimeout=30000

hikari.connectionTimeout=20000
