
# MYSQL Configuration
driver=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://localhost:3306/bluescope
username=root
password=root

# HikariCP Configuration

# Maximum no of db connections exists in the pool at a time
hikari.maximumPoolSize=10

# Atleast 2 connections ready to connect
hikari.minimumIdle=2

# If more than 2 connections stay idle for 30 seconds, the extra ones are closed.
# 1 second = 1000 milliseconds
hikari.idleTimeout=30000

# Maximum time the application waits to obtain a connection from the pool
# If application not connected with anything then its throwing an error.
hikari.connectionTimeout=20000